In [1]:
import psycopg2
import pandas as pd
import datetime
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.experimental import enable_halving_search_cv  # noqa
from sklearn.model_selection import HalvingGridSearchCV

In [2]:
params = params = {
    "host": "localhost",
    "user": "postgres",
    "port": 5432,
    #"password": "şifre" 
}
connection = psycopg2.connect(**params, dbname= "postgres")

In [3]:
df = pd.read_sql("select * from public.spotify_log sl join public.spotify_track st on sl.track_id_clean = st.track_id;", connection)

/Users/hasanenesguray/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [4]:
df.head()

,session_id,session_position,session_length,track_id_clean,skip_1,skip_2,skip_3,not_skipped,context_switch,no_pause_before_play,...,time_signature,valence,acoustic_vector_0,acoustic_vector_1,acoustic_vector_2,acoustic_vector_3,acoustic_vector_4,acoustic_vector_5,acoustic_vector_6,acoustic_vector_7
0,0_00006f66-33e5-4de7-a324-2d18e439fc1e,3,20,t_fc5df5ba-5396-49a7-8b29-35d0d28249e0,False,False,False,True,0,1,...,4,0.373862,-0.742541,0.375599,0.252660,-0.049007,-0.299745,0.063341,-0.486689,0.181604
1,0_00006f66-33e5-4de7-a324-2d18e439fc1e,10,20,t_2af4dfa0-7df3-4b7e-b7ab-353ba48237f9,True,True,True,False,0,1,...,4,0.257672,-0.647221,0.316101,0.251329,-0.041532,-0.252359,0.059971,-0.313696,0.126421
2,0_00006f66-33e5-4de7-a324-2d18e439fc1e,11,20,t_79570b2a-639a-4ec0-9853-71c5299ac44d,True,True,True,False,0,1,...,4,0.037998,-0.573548,0.284808,0.249904,-0.080877,-0.337629,0.116421,-0.337717,0.247187
3,0_00006f66-33e5-4de7-a324-2d18e439fc1e,17,20,t_bff5b6c6-6968-41be-b723-7e860b372975,False,True,True,False,0,1,...,4,0.283693,-0.837439,0.368295,0.271468,0.024429,-0.292806,0.032801,-0.485078,0.183784
4,0_0000a72b-09ac-412f-b452-9b9e79bded8f,2,20,t_0632570b-b4b4-4c3c-b47c-443ec9fbaa11,True,True,True,False,0,1,...,4,0.555482,0.203349,0.247835,-0.136071,-0.440866,0.680082,0.181352,-0.279335,0.001125

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167880 entries, 0 to 167879
Data columns (total 51 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   session_id                       167880 non-null  object
 1   session_position                 167880 non-null  int64
 2   session_length                   167880 non-null  int64
 3   track_id_clean                   167880 non-null  object
 4   skip_1                           167880 non-null  bool
 5   skip_2                           167880 non-null  bool
 6   skip_3                           167880 non-null  bool
 7   not_skipped                      167880 non-null  bool
 8   context_switch                   167880 non-null  int64
 9   no_pause_before_play             167880 non-null  int64
 10  short_pause_before_play          167880 non-null  int64
 11  long_pause_before_play           167880 non-null  int64
 12  hist_user_behavior_n_seekfwd     167880 non-null  int64
 13  hist_user_behavior_n_seekback    167880 non-null  int64
 14  hist_user_behavior_is_shuffle    167880 non-null  bool
 15  hour_of_day                      167880 non-null  int64
 16  date                             167880 non-null  object
 17  premium                          167880 non-null  bool
 18  context_type                     167880 non-null  object
 19  hist_user_behavior_reason_start  167880 non-null  object
 20  hist_user_behavior_reason_end    167880 non-null  object
 21  track_id                         167880 non-null  object
 22  duration                         167880 non-null  float64
 23  release_year                     167880 non-null  int64
 24  us_popularity_estimate           167880 non-null  float64
 25  acousticness                     167880 non-null  float64
 26  beat_strength                    167880 non-null  float64
 27  bounciness                       167880 non-null  float64
 28  danceability                     167880 non-null  float64
 29  dyn_range_mean                   167880 non-null  float64
 30  energy                           167880 non-null  float64
 31  flatness                         167880 non-null  float64
 32  instrumentalness                 167880 non-null  float64
 33  key                              167880 non-null  int64
 34  liveness                         167880 non-null  float64
 35  loudness                         167880 non-null  float64
 36  mechanism                        167880 non-null  float64
 37  mode                             167880 non-null  object
 38  organism                         167880 non-null  float64
 39  speechiness                      167880 non-null  float64
 40  tempo                            167880 non-null  float64
 41  time_signature                   167880 non-null  int64
 42  valence                          167880 non-null  float64
 43  acoustic_vector_0                167880 non-null  float64
 44  acoustic_vector_1                167880 non-null  float64
 45  acoustic_vector_2                167880 non-null  float64
 46  acoustic_vector_3                167880 non-null  float64
 47  acoustic_vector_4                167880 non-null  float64
 48  acoustic_vector_5                167880 non-null  float64
 49  acoustic_vector_6                167880 non-null  float64
 50  acoustic_vector_7                167880 non-null  float64
dtypes: bool(6), float64(25), int64(12), object(8)
memory usage: 58.6+ MB

In [6]:
df.date.unique()

array(['2018-07-15', '2018-07-14', '2018-07-13', '2018-07-12',
       '2018-06-05', '2018-07-11', '2018-07-16', '2018-07-10',
       '2018-07-04', '2018-07-05', '2018-07-07', '2018-07-06',
       '2018-05-12', '2018-07-09', '2018-06-29', '2018-06-30',
       '2018-06-19', '2018-05-18'], dtype=object)

In [7]:
def weekday_converter(date):
    format = '%Y-%m-%d'
    datetime_date = datetime.datetime.strptime(date,format)
    weekdays_list = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
    return weekdays_list[datetime_date.weekday()]

df = df.assign(weekday=df.date.apply(weekday_converter))
df.head()

,session_id,session_position,session_length,track_id_clean,skip_1,skip_2,skip_3,not_skipped,context_switch,no_pause_before_play,...,valence,acoustic_vector_0,acoustic_vector_1,acoustic_vector_2,acoustic_vector_3,acoustic_vector_4,acoustic_vector_5,acoustic_vector_6,acoustic_vector_7,weekday
0,0_00006f66-33e5-4de7-a324-2d18e439fc1e,3,20,t_fc5df5ba-5396-49a7-8b29-35d0d28249e0,False,False,False,True,0,1,...,0.373862,-0.742541,0.375599,0.252660,-0.049007,-0.299745,0.063341,-0.486689,0.181604,Sunday
1,0_00006f66-33e5-4de7-a324-2d18e439fc1e,10,20,t_2af4dfa0-7df3-4b7e-b7ab-353ba48237f9,True,True,True,False,0,1,...,0.257672,-0.647221,0.316101,0.251329,-0.041532,-0.252359,0.059971,-0.313696,0.126421,Sunday
2,0_00006f66-33e5-4de7-a324-2d18e439fc1e,11,20,t_79570b2a-639a-4ec0-9853-71c5299ac44d,True,True,True,False,0,1,...,0.037998,-0.573548,0.284808,0.249904,-0.080877,-0.337629,0.116421,-0.337717,0.247187,Sunday
3,0_00006f66-33e5-4de7-a324-2d18e439fc1e,17,20,t_bff5b6c6-6968-41be-b723-7e860b372975,False,True,True,False,0,1,...,0.283693,-0.837439,0.368295,0.271468,0.024429,-0.292806,0.032801,-0.485078,0.183784,Sunday
4,0_0000a72b-09ac-412f-b452-9b9e79bded8f,2,20,t_0632570b-b4b4-4c3c-b47c-443ec9fbaa11,True,True,True,False,0,1,...,0.555482,0.203349,0.247835,-0.136071,-0.440866,0.680082,0.181352,-0.279335,0.001125,Sunday

In [8]:
def track_age_calculator(year):
    return 2022-year

df = df.assign(track_age=df.release_year.apply(track_age_calculator))
df[['release_year','track_age']]

        release_year  track_age
0               2018          4
1               2018          4
2               2018          4
3               2018          4
4               1974         48
...              ...        ...
167875          2015          7
167876          2018          4
167877          2018          4
167878          2018          4
167879          2018          4

[167880 rows x 2 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167880 entries, 0 to 167879
Data columns (total 53 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   session_id                       167880 non-null  object
 1   session_position                 167880 non-null  int64
 2   session_length                   167880 non-null  int64
 3   track_id_clean                   167880 non-null  object
 4   skip_1                           167880 non-null  bool
 5   skip_2                           167880 non-null  bool
 6   skip_3                           167880 non-null  bool
 7   not_skipped                      167880 non-null  bool
 8   context_switch                   167880 non-null  int64
 9   no_pause_before_play             167880 non-null  int64
 10  short_pause_before_play          167880 non-null  int64
 11  long_pause_before_play           167880 non-null  int64
 12  hist_user_behavior_n_seekfwd     167880 non-null  int64
 13  hist_user_behavior_n_seekback    167880 non-null  int64
 14  hist_user_behavior_is_shuffle    167880 non-null  bool
 15  hour_of_day                      167880 non-null  int64
 16  date                             167880 non-null  object
 17  premium                          167880 non-null  bool
 18  context_type                     167880 non-null  object
 19  hist_user_behavior_reason_start  167880 non-null  object
 20  hist_user_behavior_reason_end    167880 non-null  object
 21  track_id                         167880 non-null  object
 22  duration                         167880 non-null  float64
 23  release_year                     167880 non-null  int64
 24  us_popularity_estimate           167880 non-null  float64
 25  acousticness                     167880 non-null  float64
 26  beat_strength                    167880 non-null  float64
 27  bounciness                       167880 non-null  float64
 28  danceability                     167880 non-null  float64
 29  dyn_range_mean                   167880 non-null  float64
 30  energy                           167880 non-null  float64
 31  flatness                         167880 non-null  float64
 32  instrumentalness                 167880 non-null  float64
 33  key                              167880 non-null  int64
 34  liveness                         167880 non-null  float64
 35  loudness                         167880 non-null  float64
 36  mechanism                        167880 non-null  float64
 37  mode                             167880 non-null  object
 38  organism                         167880 non-null  float64
 39  speechiness                      167880 non-null  float64
 40  tempo                            167880 non-null  float64
 41  time_signature                   167880 non-null  int64
 42  valence                          167880 non-null  float64
 43  acoustic_vector_0                167880 non-null  float64
 44  acoustic_vector_1                167880 non-null  float64
 45  acoustic_vector_2                167880 non-null  float64
 46  acoustic_vector_3                167880 non-null  float64
 47  acoustic_vector_4                167880 non-null  float64
 48  acoustic_vector_5                167880 non-null  float64
 49  acoustic_vector_6                167880 non-null  float64
 50  acoustic_vector_7                167880 non-null  float64
 51  weekday                          167880 non-null  object
 52  track_age                        167880 non-null  int64
dtypes: bool(6), float64(25), int64(13), object(9)
memory usage: 61.2+ MB

In [10]:
df.drop('session_id', inplace=True, axis=1)
df.drop('track_id_clean', inplace=True, axis=1)
df.drop('skip_1', inplace=True, axis=1)
df.drop('skip_3', inplace=True, axis=1)
df.drop('not_skipped', inplace=True, axis=1)
df.drop('date', inplace=True, axis=1)
df.drop('track_id', inplace=True, axis=1)

In [11]:
df.drop('context_type', inplace=True, axis=1)
df.drop('hist_user_behavior_reason_start', inplace=True, axis=1)
df.drop('hist_user_behavior_reason_end', inplace=True, axis=1)
df.drop('weekday', inplace=True, axis=1)
df.drop('mode', inplace=True, axis=1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167880 entries, 0 to 167879
Data columns (total 41 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   session_position               167880 non-null  int64
 1   session_length                 167880 non-null  int64
 2   skip_2                         167880 non-null  bool
 3   context_switch                 167880 non-null  int64
 4   no_pause_before_play           167880 non-null  int64
 5   short_pause_before_play        167880 non-null  int64
 6   long_pause_before_play         167880 non-null  int64
 7   hist_user_behavior_n_seekfwd   167880 non-null  int64
 8   hist_user_behavior_n_seekback  167880 non-null  int64
 9   hist_user_behavior_is_shuffle  167880 non-null  bool
 10  hour_of_day                    167880 non-null  int64
 11  premium                        167880 non-null  bool
 12  duration                       167880 non-null  float64
 13  release_year                   167880 non-null  int64
 14  us_popularity_estimate         167880 non-null  float64
 15  acousticness                   167880 non-null  float64
 16  beat_strength                  167880 non-null  float64
 17  bounciness                     167880 non-null  float64
 18  danceability                   167880 non-null  float64
 19  dyn_range_mean                 167880 non-null  float64
 20  energy                         167880 non-null  float64
 21  flatness                       167880 non-null  float64
 22  instrumentalness               167880 non-null  float64
 23  key                            167880 non-null  int64
 24  liveness                       167880 non-null  float64
 25  loudness                       167880 non-null  float64
 26  mechanism                      167880 non-null  float64
 27  organism                       167880 non-null  float64
 28  speechiness                    167880 non-null  float64
 29  tempo                          167880 non-null  float64
 30  time_signature                 167880 non-null  int64
 31  valence                        167880 non-null  float64
 32  acoustic_vector_0              167880 non-null  float64
 33  acoustic_vector_1              167880 non-null  float64
 34  acoustic_vector_2              167880 non-null  float64
 35  acoustic_vector_3              167880 non-null  float64
 36  acoustic_vector_4              167880 non-null  float64
 37  acoustic_vector_5              167880 non-null  float64
 38  acoustic_vector_6              167880 non-null  float64
 39  acoustic_vector_7              167880 non-null  float64
 40  track_age                      167880 non-null  int64
dtypes: bool(3), float64(25), int64(13)
memory usage: 49.2 MB

In [13]:
df["skip_2"] = df["skip_2"].astype(int)
df["hist_user_behavior_is_shuffle"] = df["hist_user_behavior_is_shuffle"].astype(int)
df["premium"] = df["premium"].astype(int)

In [14]:
target_count = df.skip_2.value_counts(normalize=True)
target_count

1    0.517179
0    0.482821
Name: skip_2, dtype: float64

In [15]:
columns = df.columns.tolist()
columns = [columns[2]] + columns[0:2] + columns[3:]
df = df[columns]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167880 entries, 0 to 167879
Data columns (total 41 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   skip_2                         167880 non-null  int64
 1   session_position               167880 non-null  int64
 2   session_length                 167880 non-null  int64
 3   context_switch                 167880 non-null  int64
 4   no_pause_before_play           167880 non-null  int64
 5   short_pause_before_play        167880 non-null  int64
 6   long_pause_before_play         167880 non-null  int64
 7   hist_user_behavior_n_seekfwd   167880 non-null  int64
 8   hist_user_behavior_n_seekback  167880 non-null  int64
 9   hist_user_behavior_is_shuffle  167880 non-null  int64
 10  hour_of_day                    167880 non-null  int64
 11  premium                        167880 non-null  int64
 12  duration                       167880 non-null  float64
 13  release_year                   167880 non-null  int64
 14  us_popularity_estimate         167880 non-null  float64
 15  acousticness                   167880 non-null  float64
 16  beat_strength                  167880 non-null  float64
 17  bounciness                     167880 non-null  float64
 18  danceability                   167880 non-null  float64
 19  dyn_range_mean                 167880 non-null  float64
 20  energy                         167880 non-null  float64
 21  flatness                       167880 non-null  float64
 22  instrumentalness               167880 non-null  float64
 23  key                            167880 non-null  int64
 24  liveness                       167880 non-null  float64
 25  loudness                       167880 non-null  float64
 26  mechanism                      167880 non-null  float64
 27  organism                       167880 non-null  float64
 28  speechiness                    167880 non-null  float64
 29  tempo                          167880 non-null  float64
 30  time_signature                 167880 non-null  int64
 31  valence                        167880 non-null  float64
 32  acoustic_vector_0              167880 non-null  float64
 33  acoustic_vector_1              167880 non-null  float64
 34  acoustic_vector_2              167880 non-null  float64
 35  acoustic_vector_3              167880 non-null  float64
 36  acoustic_vector_4              167880 non-null  float64
 37  acoustic_vector_5              167880 non-null  float64
 38  acoustic_vector_6              167880 non-null  float64
 39  acoustic_vector_7              167880 non-null  float64
 40  track_age                      167880 non-null  int64
dtypes: float64(25), int64(16)
memory usage: 52.5 MB

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], 
                                                    test_size = 0.3, random_state=42)

In [17]:
print(X_train.shape) # Eğitim için %70 
print(X_test.shape) # Test için %30

(117516, 40)
(50364, 40)

In [18]:
print(y_train.shape)
print(y_test.shape)

(117516,)
(50364,)

In [19]:
#knn = KNeighborsClassifier(n_neighbors=5)
#knn.fit(X_train, y_train)
#y_pred = knn.predict(X_test)

#print(metrics.accuracy_score(y_test, y_pred))

In [20]:
#knn = KNeighborsClassifier(n_neighbors=1)
#knn.fit(X_train, y_train)
#y_pred = knn.predict(X_test)

#print(metrics.accuracy_score(y_test, y_pred))

In [21]:
knn = KNeighborsClassifier(n_neighbors=5)
#scores = cross_val_score(knn, df.iloc[:, 1:], df.iloc[:, 0], cv=10, scoring='accuracy') # Veri setini 10 farklı formatta hazırla
#print(scores)

In [22]:
# Elde ettiğimiz bu accuracy değerlerinden bir çıkarım yapabilmek için aritmetik ortalama almak oldukça mantıklı bir yöntem
#print(scores.mean())

In [23]:
# Hangi parametrelerin değerlendirileceğini tanımlama
k_range = list(range(3,9,2))
weight_options = ['uniform', 'distance']
metric_options = ['euclidean', 'manhattan', 'minkowski']

In [24]:
param_dist = dict(n_neighbors=k_range, weights=weight_options, metric=metric_options)

In [25]:
rand = HalvingGridSearchCV(knn, param_dist, scoring='accuracy', n_jobs=-1, min_resources="exhaust",factor = 3)
rand.fit(df.iloc[:, 1:], df.iloc[:, 0])
rand.cv_results_

{'iter': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 2, 2]),
 'n_resources': array([ 18653,  18653,  18653,  18653,  18653,  18653,  18653,  18653,
         18653,  18653,  18653,  18653,  18653,  18653,  18653,  18653,
         18653,  18653,  55959,  55959,  55959,  55959,  55959,  55959,
        167877, 167877]),
 'mean_fit_time': array([0.04519458, 0.23499022, 0.21171813, 0.88168383, 0.96838498,
        0.38363185, 0.32110815, 0.24131274, 0.49822979, 0.32747989,
        0.41096482, 0.41815438, 0.33733306, 0.96388788, 0.46296458,
        0.54907517, 0.78184967, 0.78429613, 0.17047224, 0.55273914,
        1.62733607, 2.03236117, 0.73971567, 0.37573447, 0.22810307,
        1.00537481]),
 'std_fit_time': array([0.01766051, 0.16836485, 0.14901327, 0.44056257, 0.80255918,
        0.55320076, 0.19785729, 0.17845802, 0.29725956, 0.18555149,
        0.17137523, 0.39835569, 0.42922578, 0.36918812, 0.36434888,
        0.32313615, 0.38738613, 0.44052493, 0.01311485, 0.62558334,
        0.42603978, 1.05730719, 0.560096  , 0.13868765, 0.0300827 ,
        0.99246744]),
 'mean_score_time': array([   8.71380301,    5.05863385,    5.86304336,    2.39276628,
           3.09201379,    2.15273933,    5.34392676,    2.02073879,
           2.10381036,    3.53751907,    2.59608669,   10.7773397 ,
           1.72899837,    2.47853599,    2.51185713,    2.54887686,
           2.56499076,    4.03195968,  421.94705997,  245.64294524,
         120.68661408,  160.30478697,  137.63254175,  177.2678102 ,
        1284.94425378,  851.54064403]),
 'std_score_time': array([4.74234723e-02, 2.74334243e+00, 2.14496234e+00, 1.47730536e+00,
        1.71166220e+00, 2.49704161e-01, 4.96458815e+00, 6.86550648e-02,
        2.63444256e-01, 2.23384376e-01, 5.10049547e-01, 5.89691742e+00,
        3.55299075e-02, 6.16175089e-01, 5.15076514e-01, 6.76219476e-01,
        7.93052933e-01, 4.24779786e+00, 1.42801008e+01, 1.74168533e+02,
        6.40833777e+01, 3.01915993e+01, 5.79445496e+01, 8.34022675e+00,
        4.43618739e+02, 1.58119960e+02]),
 'param_metric': masked_array(data=['euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'euclidean',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'minkowski', 'euclidean'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_n_neighbors': masked_array(data=[3, 3, 5, 5, 7, 7, 3, 3, 5, 5, 7, 7, 3, 3, 5, 5, 7, 7,
                    7, 7, 5, 7, 5, 7, 7, 7],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'uniform',
                    'distance', 'distance', 'uniform', 'uniform',
                    'uniform', 'uniform'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'},
  {'metric': 'minkowski', 'n_neighbors': 3, 'weights': 'uniform'},
  {'metric': 'minkowski', 'n_neighbors': 3, 'weights': 'distance'},
  {'metric': 'minkowski', 'n_neighbors': 5, 'weights': 'uniform'},
  {'metric': 'minkowski', 'n_neighbors': 5, 'weights': 'distance'},
  {'metric': 'minkowski', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'minkowski', 'n_neighbors': 7, 'weights': 'distance'},
  {'metric': 'minkowski', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'minkowski', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'uniform'}],
 'split0_test_score': array([0.51099196, 0.51179625, 0.52171582, 0.51715818, 0.51957105,
        0.51903485, 0.5227882 , 0.52198391, 0.52788204, 0.52171582,
        0.51742627, 0.51635389, 0.51099196, 0.51179625, 0.52171582,
        0.51715818, 0.51957105, 0.51903485, 0.52506478, 0.52506478,
        0.52023948, 0.52238406, 0.52149048, 0.52363506, 0.52551005,
        0.52551005]),
 'split1_test_score': array([0.50589812, 0.50187668, 0.51367292, 0.51340483, 0.51608579,
        0.51394102, 0.50428954, 0.50321716, 0.51689008, 0.51796247,
        0.52680965, 0.52359249, 0.50589812, 0.50187668, 0.51367292,
        0.51340483, 0.51608579, 0.51394102, 0.52569029, 0.52569029,
        0.51344831, 0.52095434, 0.51389509, 0.52372442, 0.5267312 ,
        0.5267312 ]),
 'split2_test_score': array([0.52010724, 0.51796247, 0.5150134 , 0.51474531, 0.52010724,
        0.52064343, 0.50723861, 0.5077748 , 0.5152815 , 0.51447721,
        0.50911528, 0.51045576, 0.52010724, 0.51796247, 0.5150134 ,
        0.51474531, 0.52010724, 0.52064343, 0.50960593, 0.50960593,
        0.50352962, 0.50933786, 0.50656778, 0.51183987, 0.51883842,
        0.51883842]),
 'split3_test_score': array([0.50241287, 0.50187668, 0.50107239, 0.50187668, 0.51581769,
        0.5152815 , 0.49946381, 0.49731903, 0.51742627, 0.51447721,
        0.5227882 , 0.51849866, 0.50241287, 0.50187668, 0.50107239,
        0.50187668, 0.51581769, 0.5152815 , 0.51264409, 0.51264409,
        0.51121437, 0.50996336, 0.51175051, 0.51112501, 0.51639613,
        0.51639613]),
 'split4_test_score': array([0.49758713, 0.49812332, 0.4922252 , 0.4919571 , 0.50080429,
        0.5       , 0.50965147, 0.50884718, 0.51152815, 0.51099196,
        0.51823056, 0.51769437, 0.49758713, 0.49812332, 0.4922252 ,
        0.4919571 , 0.50080429, 0.5       , 0.51389509, 0.51389509,
        0.51353766, 0.51434188, 0.51192923, 0.51326959, 0.51505585,
        0.51505585]),
 'mean_test_score': array([0.50739946, 0.50632708, 0.50873995, 0.50782842, 0.51447721,
        0.51378016, 0.50868633, 0.50782842, 0.51780161, 0.51592493,
        0.51887399, 0.51731903, 0.50739946, 0.50632708, 0.50873995,
        0.50782842, 0.51447721, 0.51378016, 0.51738004, 0.51738004,
        0.51239389, 0.5153963 , 0.51312662, 0.51671879, 0.52050633,
        0.52050633]),
 'std_test_score': array([0.00771746, 0.00737845, 0.01061689, 0.00952162, 0.00705659,
        0.00730601, 0.00782658, 0.00816247, 0.00544599, 0.00363901,
        0.0059336 , 0.00421722, 0.00771746, 0.00737845, 0.01061689,
        0.00952162, 0.00705659, 0.00730601, 0.00668021, 0.00668021,
        0.00536544, 0.00542317, 0.00483509, 0.00572547, 0.00475751,
        0.00475751]),
 'rank_test_score': array([23, 25, 17, 20, 11, 13, 19, 20,  4,  9,  3,  7, 23, 25, 17, 20, 11,
        13,  5,  5, 16, 10, 15,  8,  1,  1], dtype=int32),
 'split0_train_score': array([0.75579681, 0.99966492, 0.69367377, 0.99966492, 0.66097038,
        0.99966492, 0.76363758, 0.99966492, 0.69534915, 0.99966492,
        0.66780592, 0.99966492, 0.75579681, 0.99966492, 0.69367377,
        0.99966492, 0.66097038, 0.99966492, 0.6712087 , 0.6712087 ,
        0.99895012, 0.99895012, 0.70156589, 0.67123104, 0.66797716,
        0.66797716]),
 'split1_train_score': array([0.75103873, 0.99926283, 0.68971988, 0.99926283, 0.66204262,
        0.99926283, 0.7548586 , 0.99926283, 0.694679  , 0.99926283,
        0.66472323, 0.99926283, 0.75103873, 0.99926283, 0.68971988,
        0.99926283, 0.66204262, 0.99926283, 0.66370317, 0.66370317,
        0.99865973, 0.99865973, 0.6963835 , 0.66712087, 0.66588484,
        0.66588484]),
 'split2_train_score': array([0.75606487, 0.99892776, 0.69782871, 0.99892776, 0.66465621,
        0.99892776, 0.75834339, 0.99892776, 0.699102  , 0.99892776,
        0.67330117, 0.99892776, 0.75606487, 0.99892776, 0.69782871,
        0.99892776, 0.66465621, 0.99892776, 0.66924297, 0.66924297,
        0.99667166, 0.99667166, 0.69982353, 0.67029285, 0.66864729,
        0.66864729]),
 'split3_train_score': array([0.75050261, 0.99899477, 0.68837957, 0.99899477, 0.663718  ,
        0.99899477, 0.74855917, 0.99899477, 0.69501407, 0.99899477,
        0.66760488, 0.99899477, 0.75050261, 0.99899477, 0.68837957,
        0.99899477, 0.663718  , 0.99899477, 0.66814841, 0.66814841,
        0.99653763, 0.99653763, 0.69953314, 0.67087363, 0.66751551,
        0.66751551]),
 'split4_train_score': array([0.75499263, 0.99859268, 0.69414288, 0.99859268, 0.66479024,
        0.99859268, 0.75861145, 0.99859268, 0.69608632, 0.99859268,
        0.66586248, 0.99859268, 0.75499263, 0.99859268, 0.69414288,
        0.99859268, 0.66479024, 0.99859268, 0.66419461, 0.66419461,
        0.99644828, 0.99644828, 0.6985056 , 0.66716555, 0.66712087,
        0.66712087]),
 'mean_train_score': array([0.75367913, 0.99908859, 0.69274896, 0.99908859, 0.66323549,
        0.99908859, 0.75680204, 0.99908859, 0.69604611, 0.99908859,
        0.66785954, 0.99908859, 0.75367913, 0.99908859, 0.69274896,
        0.99908859, 0.66323549, 0.99908859, 0.66729957, 0.66729957,
        0.99745348, 0.99745348, 0.69916233, 0.66933679, 0.66742913,
        0.66742913]),
 'std_train_score': array([0.0024068 , 0.00035864, 0.00337251, 0.00035864, 0.00149814,
        0.00035864, 0.00498189, 0.00035864, 0.00159749, 0.00035864,
        0.0029497 , 0.00035864, 0.0024068 , 0.00035864, 0.00337251,
        0.00035864, 0.00149814, 0.00035864, 0.00291045, 0.00291045,
        0.00110954, 0.00110954, 0.00170323, 0.00181597, 0.00092429,
        0.00092429])}

In [28]:
def examine_results(model_grid):
    print("rank_test_score", model_grid.cv_results_['rank_test_score'])
    print("mean_test_score", model_grid.cv_results_['mean_test_score'])
    
examine_results(rand)

rank_test_score [23 25 17 20 11 13 19 20  4  9  3  7 23 25 17 20 11 13  5  5 16 10 15  8
  1  1]
mean_test_score [0.50739946 0.50632708 0.50873995 0.50782842 0.51447721 0.51378016
 0.50868633 0.50782842 0.51780161 0.51592493 0.51887399 0.51731903
 0.50739946 0.50632708 0.50873995 0.50782842 0.51447721 0.51378016
 0.51738004 0.51738004 0.51239389 0.5153963  0.51312662 0.51671879
 0.52050633 0.52050633]

In [29]:
print('Best Score:', rand.best_score_, 'Best Parameters:', rand.best_params_)

Best Score: 0.520506329113924 Best Parameters: {'metric': 'minkowski', 'n_neighbors': 7, 'weights': 'uniform'}